#import "PElements.h"


@interface PElements ()

- (NSMutableArray*) loadElements;

@end


@implementation PElements

@synthesize elements;

- (id) init 
{
	self = [super init];
	self.elements = [self loadElements];
	return self;
}

+ (float) sumWeightsOfElements: (NSArray*) elementsToAdd
{
	[elementsToAdd retain];
	float weight = 0.0;
	for (PEquationElement* element in elementsToAdd) {
        float elementWeight = [element count] * [[element element] weight];
		weight += elementWeight;
	}
	[elementsToAdd release];
	return weight;
}

- (NSMutableArray*) loadElements
{
	return [NSMutableArray arrayWithObjects:
            [PElement elementWithNumber: 1   abbreviation:@"H"   groupNumber: 1   groupName:@"I A"          period: 1 name:@"hydrogen"      roundedMass: 1      mass: 1.00794    meltingPoint: -259.1 boilingPoint: -252.9 density: 0.0000699 electroNegativity: 2.2 firstIonisation: 1312 electronAffinity: -73  commonOxidation:@"±1" 		    predictedConfiguration:@"1s1" 		               observedConfiguration:@"1s1"                   ],     		  	    				 		  		  		      	 
            [PElement elementWithNumber: 2   abbreviation:@"He"  groupNumber: 18  groupName:@"VIII A"       period: 1 name:@"helium"        roundedMass: 4.003  mass: 4.002602   meltingPoint: -272.2 boilingPoint: -268.9 density: 0.000179 electroNegativity:  0 firstIonisation: 	2377 electronAffinity: 0    commonOxidation:@"0" 		      predictedConfiguration:@"1s2" 		               observedConfiguration:@"1s2"                   ],   		    	   					  		    	      
            [PElement elementWithNumber: 3   abbreviation:@"Li"  groupNumber: 1   groupName:@"I A"          period: 2 name:@"lithium"       roundedMass: 6.941  mass: 6.941      meltingPoint: 180.5 boilingPoint: 	1342 density: 	0.543 electroNegativity: 		 1 firstIonisation: 	520 electronAffinity:  -60  commonOxidation:@"1" 		      predictedConfiguration:@"[He] 2s1" 		           observedConfiguration:@"[He] 2s1"              ], 		  	     	  		  		    		       
            [PElement elementWithNumber: 4   abbreviation:@"Be"  groupNumber: 2   groupName:@"II A"         period: 2 name:@"beryllium"     roundedMass: 9.012  mass: 9.012182   meltingPoint: 1278 boilingPoint: 	2970 density: 	1.85 electroNegativity: 	   1.6 firstIonisation: 899 electronAffinity:  -18  commonOxidation:@"2" 		      predictedConfiguration:@"[He] 2s2" 		           observedConfiguration:@"[He] 2s2"              ], 		  	       			  	    		       
            [PElement elementWithNumber: 5   abbreviation:@"B"   groupNumber: 13  groupName:@"III A"        period: 2 name:@"boron"         roundedMass: 10.81  mass: 10.811     meltingPoint: 2079 boilingPoint: 	2550 density: 	2.34 electroNegativity: 	   2 firstIonisation: 	801 electronAffinity:  -27  commonOxidation:@"3" 		      predictedConfiguration:@"[He] 2s2 2p1" 		       observedConfiguration:@"[He] 2s2 2p1"          ], 		  	       				  		      	    	 
            [PElement elementWithNumber: 6   abbreviation:@"C"   groupNumber: 14  groupName:@"IV A"         period: 2 name:@"carbon"        roundedMass: 12.01  mass: 12.0107    meltingPoint: 3367 boilingPoint: 	4827 density: 	2.25 electroNegativity: 	   2.6 firstIonisation: 1086 electronAffinity: -122 commonOxidation:@"±4" 		    predictedConfiguration:@"[He] 2s2 2p2" 		       observedConfiguration:@"[He] 2s2 2p2"          ],   			       			  		    		    	 
            [PElement elementWithNumber: 7   abbreviation:@"N"   groupNumber: 15  groupName:@"V A"          period: 2 name:@"nitrogen"      roundedMass: 14.01  mass: 14.0067    meltingPoint: -209.9 boilingPoint: -195.8 density: 0.00125 electroNegativity: 	 3 firstIonisation: 	1420 electronAffinity: -7   commonOxidation:@"-3" 		    predictedConfiguration:@"[He] 2s2 2p3" 		       observedConfiguration:@"[He] 2s2 2p3"          ],   		  	   				  		  		    	 
            [PElement elementWithNumber: 8   abbreviation:@"O"   groupNumber: 16  groupName:@"VI A"         period: 2 name:@"oxygen"        roundedMass: 16     mass: 15.9994    meltingPoint: -218.4 boilingPoint: -183 density: 	0.00143 electroNegativity: 	 3.4 firstIonisation: 1314 electronAffinity: -141 commonOxidation:@"-2" 		    predictedConfiguration:@"[He] 2s2 2p4" 		       observedConfiguration:@"[He] 2s2 2p4"          ],   			   				 				    		    	 
            [PElement elementWithNumber: 9   abbreviation:@"F"   groupNumber: 17  groupName:@"VII A"        period: 2 name:@"fluorine"      roundedMass: 19     mass: 18.9984032 meltingPoint: -219.8 boilingPoint: -188.1 density: 0.0017 electroNegativity: 	 4 firstIonisation: 	1681 electronAffinity: -328 commonOxidation:@"-1" 		    predictedConfiguration:@"[He] 2s2 2p5" 		       observedConfiguration:@"[He] 2s2 2p5"          ],   			   	  						  	    	 
            [PElement elementWithNumber: 10  abbreviation:@"Ne"  groupNumber: 18  groupName:@"VIII A"       period: 2 name:@"neon"          roundedMass: 20.18  mass: 20.1797    meltingPoint: -248 boilingPoint: 	-248.7 density: 0.0009 electroNegativity: 	 0 firstIonisation: 	2088 electronAffinity: 0    commonOxidation:@"0" 		      predictedConfiguration:@"[He] 2s2 2p6" 		       observedConfiguration:@"[He] 2s2 2p6"          ], 		    	   	  			  		      	    	 
            [PElement elementWithNumber: 11  abbreviation:@"Na"  groupNumber: 1   groupName:@"I A"          period: 3 name:@"sodium"        roundedMass: 22.99  mass: 22.98977   meltingPoint: 97.8 boilingPoint: 	883 density: 		0.971 electroNegativity: 		 0.9 firstIonisation: 495 electronAffinity:  -53  commonOxidation:@"1" 		      predictedConfiguration:@"[Ne] 3s1" 		           observedConfiguration:@"[Ne] 3s1"              ], 		  	     		  		    		     	 
            [PElement elementWithNumber: 12  abbreviation:@"Mg"  groupNumber: 2   groupName:@"II A"         period: 3 name:@"magnesium"     roundedMass: 24.31  mass: 24.305     meltingPoint: 649 boilingPoint: 		1090 density: 	1.74 electroNegativity: 		 1.3 firstIonisation: 735 electronAffinity:  0    commonOxidation:@"2" 		      predictedConfiguration:@"[Ne] 3s2" 		           observedConfiguration:@"[Ne] 3s2"              ], 		    	       	  		  	    		     	 
            [PElement elementWithNumber: 13  abbreviation:@"Al"  groupNumber: 13  groupName:@"III A"        period: 3 name:@"aluminum"      roundedMass: 26.98  mass: 26.981538  meltingPoint: 660 boilingPoint: 		2467 density: 	2.7 electroNegativity: 		   1.6 firstIonisation: 580 electronAffinity:  -44  commonOxidation:@"3" 		      predictedConfiguration:@"[Ne] 3s2 3p1" 		       observedConfiguration:@"[Ne] 3s2 3p1"          ], 		  	     	    		  	    	 
            [PElement elementWithNumber: 14  abbreviation:@"Si"  groupNumber: 14  groupName:@"IV A"         period: 3 name:@"silicon"       roundedMass: 28.09  mass: 28.0855    meltingPoint: 1410 boilingPoint: 	2355 density: 	2.33 electroNegativity: 		 1.9 firstIonisation: 780 electronAffinity:  -134 commonOxidation:@"±4" 		    predictedConfiguration:@"[Ne] 3s2 3p2" 		       observedConfiguration:@"[Ne] 3s2 3p2"          ],   			       			  		    		    	 
            [PElement elementWithNumber: 15  abbreviation:@"P"   groupNumber: 15  groupName:@"V A"          period: 3 name:@"phosphorus"    roundedMass: 30.97  mass: 30.973761  meltingPoint: 44.1 boilingPoint: 	280 density: 		1.82 electroNegativity: 		 2.2 firstIonisation: 1060 electronAffinity: -72  commonOxidation:@"-3" 		    predictedConfiguration:@"[Ne] 3s2 3p3" 		       observedConfiguration:@"[Ne] 3s2 3p3"          ],   		  	       	  	  		    	 
            [PElement elementWithNumber: 16  abbreviation:@"S"   groupNumber: 16  groupName:@"VI A"         period: 3 name:@"sulfur"        roundedMass: 32.07  mass: 32.065     meltingPoint: 112.8 boilingPoint: 	444.7 density: 	2.07 electroNegativity: 		 2.6 firstIonisation: 1005 electronAffinity: -200 commonOxidation:@"-2" 		    predictedConfiguration:@"[Ne] 3s2 3p4" 		       observedConfiguration:@"[Ne] 3s2 3p4"          ],   			         		  		    		    	 
            [PElement elementWithNumber: 17  abbreviation:@"Cl"  groupNumber: 17  groupName:@"VII A"        period: 3 name:@"chlorine"      roundedMass: 35.45  mass: 35.453     meltingPoint: -101 boilingPoint: 	-34.6 density: 	0.00321 electroNegativity: 	 3.2 firstIonisation: 1255 electronAffinity: -349 commonOxidation:@"-1" 		    predictedConfiguration:@"[Ne] 3s2 3p5" 		       observedConfiguration:@"[Ne] 3s2 3p5"          ],   			   				  		  	    	 
            [PElement elementWithNumber: 18  abbreviation:@"Ar"  groupNumber: 18  groupName:@"VIII A"       period: 3 name:@"argon"         roundedMass: 39.95  mass: 39.948     meltingPoint: -189.2 boilingPoint: -185.7 density: 0.00178 electroNegativity: 	 0 firstIonisation: 	1527 electronAffinity: 0    commonOxidation:@"0" 		      predictedConfiguration:@"[Ne] 3s2 3p6" 		       observedConfiguration:@"[Ne] 3s2 3p6"          ], 	      	   					  		      	    	 
            [PElement elementWithNumber: 19  abbreviation:@"K"   groupNumber: 1   groupName:@"I A"          period: 4 name:@"potassium"     roundedMass: 39.1   mass: 39.0983    meltingPoint: 63.25 boilingPoint: 	760 density: 		0.86 electroNegativity: 		 0.8 firstIonisation: 419 electronAffinity:  -48  commonOxidation:@"1" 		      predictedConfiguration:@"[Ar] 4s1" 		           observedConfiguration:@"[Ar] 4s1"              ], 		  	         	 		    		     	 
            [PElement elementWithNumber: 20  abbreviation:@"Ca"  groupNumber: 2   groupName:@"II A"         period: 4 name:@"calcium"       roundedMass: 40.08  mass: 40.078     meltingPoint: 839 boilingPoint: 		1484 density: 	1.55 electroNegativity: 		 1 firstIonisation: 	590 electronAffinity:  -186 commonOxidation:@"2" 		      predictedConfiguration:@"[Ar] 4s2" 		           observedConfiguration:@"[Ar] 4s2"              ], 			       	  		  		    		     	 
            [PElement elementWithNumber: 21  abbreviation:@"Sc"  groupNumber: 3   groupName:@"III B"        period: 4 name:@"scandium"      roundedMass: 44.96  mass: 44.95591   meltingPoint: 1541 boilingPoint: 	2832 density: 	2.99 electroNegativity: 		 1.4 firstIonisation: 633 electronAffinity:  -18  commonOxidation:@"3" 		      predictedConfiguration:@"[Ar] 4s2 3d1" 		       observedConfiguration:@"[Ar] 4s2 3d1"          ], 		  	       			  		  	     	 
            [PElement elementWithNumber: 22  abbreviation:@"Ti"  groupNumber: 4   groupName:@"IV B"         period: 4 name:@"titanium"      roundedMass: 47.87  mass: 47.867     meltingPoint: 1660 boilingPoint: 	3287 density: 	4.54 electroNegativity: 		 1.5 firstIonisation: 659 electronAffinity:  -8   commonOxidation:@"+4,3,2" 	  predictedConfiguration:@"[Ar] 4s2 3d2" 		       observedConfiguration:@"[Ar] 4s2 3d2"          ],   		  	       				  		  		     	 
            [PElement elementWithNumber: 23  abbreviation:@"V"   groupNumber: 5   groupName:@"V B"          period: 4 name:@"vanadium"      roundedMass: 50.94  mass: 50.9415    meltingPoint: 1890 boilingPoint: 	3380 density: 	6.11 electroNegativity: 		 1.6 firstIonisation: 651 electronAffinity:  -51  commonOxidation:@"+5,2,3,4"   predictedConfiguration:@"[Ar] 4s2 3d3" 		       observedConfiguration:@"[Ar] 4s2 3d3"          ],   		  	       			  		  		     	 
            [PElement elementWithNumber: 24  abbreviation:@"Cr"  groupNumber: 6   groupName:@"VI B"         period: 4 name:@"chromium"      roundedMass: 52     mass: 51.9961    meltingPoint: 1857 boilingPoint: 	2672 density: 	7.19 electroNegativity: 		 1.7 firstIonisation: 653 electronAffinity:  -65  commonOxidation:@"+3,2,6" 	  predictedConfiguration:@"[Ar] 4s2 3d4" 		       observedConfiguration:@"[Ar] 4s1 3d5"          ],   		  	       			 				  		     	 
            [PElement elementWithNumber: 25  abbreviation:@"Mn"  groupNumber: 7   groupName:@"VII B"        period: 4 name:@"manganese"     roundedMass: 54.94  mass: 54.938049  meltingPoint: 1244 boilingPoint: 	1962 density: 	7.43 electroNegativity: 		 1.6 firstIonisation: 717 electronAffinity:  0    commonOxidation:@"+2,3,4,6,7" predictedConfiguration:@"[Ar] 4s2 3d5" 		       observedConfiguration:@"[Ar] 4s2 3d5"          ], 			    	       		  	    	     	 
            [PElement elementWithNumber: 26  abbreviation:@"Fe"  groupNumber: 8   groupName:@"VIII B"       period: 4 name:@"iron"          roundedMass: 55.85  mass: 55.845     meltingPoint: 1535 boilingPoint: 	2750 density: 	7.86 electroNegativity: 		 1.8 firstIonisation: 763 electronAffinity:  -16  commonOxidation:@"3,2" 		    predictedConfiguration:@"[Ar] 4s2 3d6" 		       observedConfiguration:@"[Ar] 4s2 3d6"          ], 		  	       				  		      	     	 
            [PElement elementWithNumber: 27  abbreviation:@"Co"  groupNumber: 9   groupName:@"VIII B"       period: 4 name:@"cobalt"        roundedMass: 58.93  mass: 58.9332    meltingPoint: 1495 boilingPoint: 	2870 density: 	8.9 electroNegativity: 		   1.9 firstIonisation: 761 electronAffinity:  -64  commonOxidation:@"2,3" 		    predictedConfiguration:@"[Ar] 4s2 3d7" 		       observedConfiguration:@"[Ar] 4s2 3d7"          ], 		  	     			  		    	     	 
            [PElement elementWithNumber: 28  abbreviation:@"Ni"  groupNumber: 10  groupName:@"VIII B"       period: 4 name:@"nickel"        roundedMass: 58.69  mass: 58.6934    meltingPoint: 1453 boilingPoint: 	2730 density: 	8.9 electroNegativity: 		   1.9 firstIonisation: 737 electronAffinity:  -156 commonOxidation:@"2,3" 		    predictedConfiguration:@"[Ar] 4s2 3d8" 		       observedConfiguration:@"[Ar] 4s2 3d8"          ], 			     			  		    	    	 
            [PElement elementWithNumber: 29  abbreviation:@"Cu"  groupNumber: 11  groupName:@"I B"          period: 4 name:@"copper"        roundedMass: 63.55  mass: 63.546     meltingPoint: 1083 boilingPoint: 	2567 density: 	8.96 electroNegativity: 		 1.9 firstIonisation: 746 electronAffinity:  -118 commonOxidation:@"2,1" 		    predictedConfiguration:@"[Ar] 4s2 3d9" 		       observedConfiguration:@"[Ar] 4s1 3d10"         ], 			       				  		    		    	 
            [PElement elementWithNumber: 30  abbreviation:@"Zn"  groupNumber: 12  groupName:@"II B"         period: 4 name:@"zinc"          roundedMass: 65.41  mass: 65.409     meltingPoint: 419.6 boilingPoint: 	906 density: 		7.13 electroNegativity: 		 1.7 firstIonisation: 906 electronAffinity:  -9   commonOxidation:@"2" 		      predictedConfiguration:@"[Ar] 4s2 3d10" 	       observedConfiguration:@"[Ar] 4s2 3d10"         ],   		  	         		  		      		    	 
            [PElement elementWithNumber: 31  abbreviation:@"Ga"  groupNumber: 13  groupName:@"III A"        period: 4 name:@"gallium"       roundedMass: 69.72  mass: 69.723     meltingPoint: 29.8 boilingPoint: 	2403 density: 	5.9 electroNegativity: 		   1.8 firstIonisation: 579 electronAffinity:  -29  commonOxidation:@"3" 		      predictedConfiguration:@"[Ar] 4s2 3d10 4p1" 		 observedConfiguration:@"[Ar] 4s2 3d10 4p1"     ],   		  	     				  		    	    	 
            [PElement elementWithNumber: 32  abbreviation:@"Ge"  groupNumber: 14  groupName:@"IV A"         period: 4 name:@"germanium"     roundedMass: 72.64  mass: 72.64      meltingPoint: 947.4 boilingPoint: 	2830 density: 	5.32 electroNegativity: 		 2 firstIonisation: 	762 electronAffinity:  -116 commonOxidation:@"4,2" 		    predictedConfiguration:@"[Ar] 4s2 3d10 4p2" 		 observedConfiguration:@"[Ar] 4s2 3d10 4p2"     ],   			       	  		  	    		    	 
            [PElement elementWithNumber: 33  abbreviation:@"As"  groupNumber: 15  groupName:@"V A"          period: 4 name:@"arsenic"       roundedMass: 74.92  mass: 74.9216    meltingPoint: 817 boilingPoint: 		617 density: 		5.73 electroNegativity: 		 2.2 firstIonisation: 947 electronAffinity:  -78  commonOxidation:@"±3,+5" 		  predictedConfiguration:@"[Ar] 4s2 3d10 4p3" 		 observedConfiguration:@"[Ar] 4s2 3d10 4p3"     ],   		  	         	  		    		    	 
            [PElement elementWithNumber: 34  abbreviation:@"Se"  groupNumber: 16  groupName:@"VI A"         period: 4 name:@"selenium"      roundedMass: 78.96  mass: 78.96      meltingPoint: 217 boilingPoint: 		685 density: 		4.79 electroNegativity: 		 2.6 firstIonisation: 941 electronAffinity:  -195 commonOxidation:@"+4,-2,+6"   predictedConfiguration:@"[Ar] 4s2 3d10 4p4" 		 observedConfiguration:@"[Ar] 4s2 3d10 4p4"     ],   				         		  		  		    	 
            [PElement elementWithNumber: 35  abbreviation:@"Br"  groupNumber: 17  groupName:@"VII A"        period: 4 name:@"bromine"       roundedMass: 79.9   mass: 79.904     meltingPoint: -7.2 boilingPoint: 	58.8 density: 	3.12 electroNegativity: 		 3 firstIonisation: 	1140 electronAffinity: -325 commonOxidation:@"±1,+5" 		  predictedConfiguration:@"[Ar] 4s2 3d10 4p5" 		 observedConfiguration:@"[Ar] 4s2 3d10 4p5"     ],   			       				 			    	    	 
            [PElement elementWithNumber: 36  abbreviation:@"Kr"  groupNumber: 18  groupName:@"VIII A"       period: 4 name:@"krypton"       roundedMass: 83.8   mass: 83.798     meltingPoint: -157 boilingPoint: 	-152 density: 	0.00374 electroNegativity: 	 3 firstIonisation: 	1356 electronAffinity: 0    commonOxidation:@"0" 		      predictedConfiguration:@"[Ar] 4s2 3d10 4p6" 		 observedConfiguration:@"[Ar] 4s2 3d10 4p6"     ],   		    	   					 			    	    	 
            [PElement elementWithNumber: 37  abbreviation:@"Rb"  groupNumber: 1   groupName:@"I A"          period: 5 name:@"rubidium"      roundedMass: 85.47  mass: 85.4678    meltingPoint: 38.9 boilingPoint: 	686 density: 		1.53 electroNegativity: 		 0.8 firstIonisation: 409 electronAffinity:  -47  commonOxidation:@"1" 		      predictedConfiguration:@"[Kr] 5s2" 		           observedConfiguration:@"[Kr] 5s2"              ],		  	       		  		  		     	 
            [PElement elementWithNumber: 38  abbreviation:@"Sr"  groupNumber: 2   groupName:@"II A"         period: 5 name:@"strontium"     roundedMass: 87.62  mass: 87.62      meltingPoint: 769 boilingPoint: 		1384 density: 	2.54 electroNegativity: 		 1 firstIonisation: 	550 electronAffinity:  -146 commonOxidation:@"2" 		      predictedConfiguration:@"[Kr] 5s2" 		           observedConfiguration:@"[Kr] 5s2"              ],			       	  		  	    		     	 
            [PElement elementWithNumber: 39  abbreviation:@"Y"   groupNumber: 3   groupName:@"III B"        period: 5 name:@"yttrium"       roundedMass: 88.91  mass: 88.90585   meltingPoint: 1523 boilingPoint: 	3337 density: 	4.47 electroNegativity: 		 1.2 firstIonisation: 600 electronAffinity:  -30  commonOxidation:@"3" 		      predictedConfiguration:@"[Kr] 5s2 4d1" 		       observedConfiguration:@"[Kr] 5s2 4d1"          ], 		  	       			  		    	     	 
            [PElement elementWithNumber: 40  abbreviation:@"Zr"  groupNumber: 4   groupName:@"IV B"         period: 5 name:@"zirconium"     roundedMass: 91.22  mass: 91.224     meltingPoint: 1852 boilingPoint: 	4377 density: 	6.51 electroNegativity: 		 1.3 firstIonisation: 640 electronAffinity:  -41  commonOxidation:@"4" 		      predictedConfiguration:@"[Kr] 5s2 4d2" 		       observedConfiguration:@"[Kr] 5s2 4d2"          ], 		  	       				  	    		     	 
            [PElement elementWithNumber: 41  abbreviation:@"Nb"  groupNumber: 5   groupName:@"VI B"         period: 5 name:@"niobium"       roundedMass: 92.91  mass: 92.90638   meltingPoint: 2468 boilingPoint: 	4742 density: 	8.57 electroNegativity: 		 1.6 firstIonisation: 652 electronAffinity:  -87  commonOxidation:@"5,3" 		    predictedConfiguration:@"[Kr] 5s2 4d3" 		       observedConfiguration:@"[Kr] 5s1 4d4"          ], 		  	       			  		    		     	 
            [PElement elementWithNumber: 42  abbreviation:@"Mo"  groupNumber: 6   groupName:@"VI B"         period: 5 name:@"molybdenum"    roundedMass: 95.94  mass: 95.94      meltingPoint: 2617 boilingPoint: 	4612 density: 	10.2 electroNegativity: 		 2.2 firstIonisation: 684 electronAffinity:  -72  commonOxidation:@"+6,3,5" 	  predictedConfiguration:@"[Kr] 5s2 4d4" 		       observedConfiguration:@"[Kr] 5s1 4d5"          ],   		  	       				  	  		     	 
            [PElement elementWithNumber: 43  abbreviation:@"Tc"  groupNumber: 7   groupName:@"VII B"        period: 5 name:@"technetium"    roundedMass: 98     mass: 98         meltingPoint: 2172 boilingPoint: 	4877 density: 	11.5 electroNegativity: 		 1.9 firstIonisation: 702 electronAffinity:  -96  commonOxidation:@"+7,4,6" 	  predictedConfiguration:@"[Kr] 5s2 4d5" 		       observedConfiguration:@"[Kr] 5s2 4d5"          ],   		  	       				     			  	     	 
            [PElement elementWithNumber: 44  abbreviation:@"Ru"  groupNumber: 8   groupName:@"VIII B"       period: 5 name:@"ruthenium"     roundedMass: 101.1  mass: 101.07     meltingPoint: 2310 boilingPoint: 	3900 density: 	12.4 electroNegativity: 		 2.2 firstIonisation: 710 electronAffinity:  -101 commonOxidation:@"+4,3,6,8"   predictedConfiguration:@"[Kr] 5s2 4d6" 		       observedConfiguration:@"[Kr] 5s1 4d7"          ], 				       				  	    	     	 
            [PElement elementWithNumber: 45  abbreviation:@"Rh"  groupNumber: 9   groupName:@"VIII B"       period: 5 name:@"rhodium"       roundedMass: 102.9  mass: 102.9055   meltingPoint: 1966 boilingPoint: 	3727 density: 	12.4 electroNegativity: 		 2.3 firstIonisation: 720 electronAffinity:  -110 commonOxidation:@"+3,4,6" 	  predictedConfiguration:@"[Kr] 5s2 4d7" 		       observedConfiguration:@"[Kr] 5s1 4d8"          ],   			       			  		    	     	 
            [PElement elementWithNumber: 46  abbreviation:@"Pd"  groupNumber: 10  groupName:@"VIII B"       period: 5 name:@"palladium"     roundedMass: 106.4  mass: 106.42     meltingPoint: 1554 boilingPoint: 	3140 density: 	12 electroNegativity: 		   2.2 firstIonisation: 804 electronAffinity:  -54  commonOxidation:@"2,4" 		    predictedConfiguration:@"[Kr] 5s2 4d8" 		       observedConfiguration:@"[Kr] (5s0) 4d10"       ], 		  	       				  	    	    	 
            [PElement elementWithNumber: 47  abbreviation:@"Ag"  groupNumber: 11  groupName:@"I B"          period: 5 name:@"silver"        roundedMass: 107.9  mass: 107.8682   meltingPoint: 962 boilingPoint: 		2212 density: 	10.5 electroNegativity: 		 1.9 firstIonisation: 731 electronAffinity:  -126 commonOxidation:@"1" 		      predictedConfiguration:@"[Kr] 5s2 4d9" 		       observedConfiguration:@"[Kr] 5s1 4d10"         ], 			       	  	  		    		    	 
            [PElement elementWithNumber: 48  abbreviation:@"Cd"  groupNumber: 12  groupName:@"II B"         period: 5 name:@"cadmium"       roundedMass: 112.4  mass: 112.411    meltingPoint: 320.9 boilingPoint: 	765 density: 		8.65 electroNegativity: 		 1.7 firstIonisation: 868 electronAffinity:  -26  commonOxidation:@"2" 		      predictedConfiguration:@"[Kr] 5s2 4d10" 		     observedConfiguration:@"[Kr] 5s2 4d10"         ],   		  	         	  		    		    	 
            [PElement elementWithNumber: 49  abbreviation:@"In"  groupNumber: 13  groupName:@"III A"        period: 5 name:@"indium"        roundedMass: 114.8  mass: 114.818    meltingPoint: 156.6 boilingPoint: 	2080 density: 	7.31 electroNegativity: 		 1.8 firstIonisation: 558 electronAffinity:  -29  commonOxidation:@"3" 		      predictedConfiguration:@"[Kr] 5s2 4d10 5p1" 		 observedConfiguration:@"[Kr] 5s2 4d10 5p1"     ],   		  	       	  	  		    	    	 
            [PElement elementWithNumber: 50  abbreviation:@"Sn"  groupNumber: 14  groupName:@"IV A"         period: 5 name:@"tin"           roundedMass: 118.7  mass: 118.71     meltingPoint: 232 boilingPoint: 		2270 density: 	7.31 electroNegativity: 		 2 firstIonisation: 	709 electronAffinity:  -116 commonOxidation:@"4,2" 		    predictedConfiguration:@"[Kr] 5s2 4d10 5p2" 		 observedConfiguration:@"[Kr] 5s2 4d10 5p2"     ],   			       	  		  		        		    	 
            [PElement elementWithNumber: 51  abbreviation:@"Sb"  groupNumber: 15  groupName:@"V A"          period: 5 name:@"antimony"      roundedMass: 121.8  mass: 121.76     meltingPoint: 631 boilingPoint: 		1950 density: 	6.69 electroNegativity: 		 2.1 firstIonisation: 834 electronAffinity:  -101 commonOxidation:@"3,5" 		    predictedConfiguration:@"[Kr] 5s2 4d10 5p3" 		 observedConfiguration:@"[Kr] 5s2 4d10 5p3"     ],   			       	  		  		  		    	 
            [PElement elementWithNumber: 52  abbreviation:@"Te"  groupNumber: 16  groupName:@"VI A"         period: 5 name:@"tellurium"     roundedMass: 127.6  mass: 127.6      meltingPoint: 449.5 boilingPoint: 	989.8 density: 	6.24 electroNegativity: 		 2.1 firstIonisation: 869 electronAffinity:  -190 commonOxidation:@"+4,6,-2" 	  predictedConfiguration:@"[Kr] 5s2 4d10 5p4" 		 observedConfiguration:@"[Kr] 5s2 4d10 5p4"     ],   			         		  	    		    	 
            [PElement elementWithNumber: 53  abbreviation:@"I"   groupNumber: 17  groupName:@"VII A"        period: 5 name:@"iodine"        roundedMass: 126.9  mass: 126.90447  meltingPoint: 113.5 boilingPoint: 	184 density: 		4.93 electroNegativity: 		 2.7 firstIonisation: 1008 electronAffinity: -295 commonOxidation:@"-1,+5,7" 	  predictedConfiguration:@"[Kr] 5s2 4d10 5p5" 		 observedConfiguration:@"[Kr] 5s2 4d10 5p5"     ],   			           		    	    	 
            [PElement elementWithNumber: 54  abbreviation:@"Xe"  groupNumber: 18  groupName:@"VIII A"       period: 5 name:@"xenon"         roundedMass: 131.3  mass: 131.293    meltingPoint: -111.8 boilingPoint: -107.1 density: 0.00589 electroNegativity: 	 2.6 firstIonisation: 1176 electronAffinity: 0    commonOxidation:@"0" 		      predictedConfiguration:@"[Kr] 5s2 4d10 5p6" 		 observedConfiguration:@"[Kr] 5s2 4d10 5p6"     ],   		    	   				  		      	    	 
            [PElement elementWithNumber: 55  abbreviation:@"Cs"  groupNumber: 1   groupName:@"I A"          period: 6 name:@"caesium"       roundedMass: 132.9  mass: 132.90545  meltingPoint: 28.4 boilingPoint: 	669 density: 		1.87 electroNegativity: 		 0.8 firstIonisation: 382 electronAffinity:  -45  commonOxidation:@"1" 		      predictedConfiguration:@"[Xe] 6s1" 		           observedConfiguration:@"[Xe] 6s1"              ], 		  	       	  		    		     	 
            [PElement elementWithNumber: 56  abbreviation:@"Ba"  groupNumber: 2   groupName:@"II A"         period: 6 name:@"barium"        roundedMass: 137.3  mass: 137.327    meltingPoint: 725 boilingPoint: 		1640 density: 	3.5 electroNegativity: 		   0.9 firstIonisation: 508 electronAffinity:  -46  commonOxidation:@"2" 		      predictedConfiguration:@"[Xe] 6s2" 		           observedConfiguration:@"[Xe] 6s2"              ], 		  	     	  	  		    		     	 
            [PElement elementWithNumber: 57  abbreviation:@"La"  groupNumber: -1  groupName:@"III B"        period: 6 name:@"lanthanum"     roundedMass: 138.9  mass: 138.9055   meltingPoint: 920 boilingPoint: 		3454 density: 	6.15 electroNegativity: 		 1.1 firstIonisation: 538 electronAffinity:  -48  commonOxidation:@"3" 		      predictedConfiguration:@"[Xe] 6s2 4f1" 		       observedConfiguration:@"[Xe] 6s2 4f1"          ], 		  	       	  	  	    	      
            [PElement elementWithNumber: 58  abbreviation:@"Ce"  groupNumber: -1  groupName:@"lanthanides"  period: 6 name:@"cerium"        roundedMass: 140.1  mass: 140.116    meltingPoint: 798 boilingPoint: 		3257 density: 	6.66 electroNegativity: 		 1.1 firstIonisation: 534 electronAffinity:  0    commonOxidation:@"3,4" 	      predictedConfiguration:@"[Xe] 6s2 4f2" 		       observedConfiguration:@"[Xe] 6s2 4f2"          ], 		    	       	  	  		      
            [PElement elementWithNumber: 59  abbreviation:@"Pr"  groupNumber: -1  groupName:@"lanthanides"  period: 6 name:@"praseodymium"  roundedMass: 140.9  mass: 140.90765  meltingPoint: 931 boilingPoint: 		3017 density: 	6.77 electroNegativity: 		 1.1 firstIonisation: 527 electronAffinity:  0    commonOxidation:@"3,4" 	      predictedConfiguration:@"[Xe] 6s2 4f3" 		       observedConfiguration:@"[Xe] 6s2 4f3"          ], 		    	       	        
            [PElement elementWithNumber: 60  abbreviation:@"Nd"  groupNumber: -1  groupName:@"lanthanides"  period: 6 name:@"neodymium"     roundedMass: 144.2  mass: 144.24     meltingPoint: 1016 boilingPoint: 	3127 density: 	7 electroNegativity: 		     1.1 firstIonisation: 533 electronAffinity:  0    commonOxidation:@"3" 		      predictedConfiguration:@"[Xe] 6s2 4f4" 		       observedConfiguration:@"[Xe] 6s2 4f4"          ], 		    	     				  		    
            [PElement elementWithNumber: 61  abbreviation:@"Pm"  groupNumber: -1  groupName:@"lanthanides"  period: 6 name:@"promethium"    roundedMass: 145    mass: 145        meltingPoint: 1042 boilingPoint: 	3000 density: 	7.26 electroNegativity: 		 0 firstIonisation: 	540 electronAffinity:  0    commonOxidation:@"3" 		      predictedConfiguration:@"[Xe] 6s2 4f5" 		       observedConfiguration:@"[Xe] 6s2 4f5"          ], 		    	       				   	  		  
            [PElement elementWithNumber: 62  abbreviation:@"Sm"  groupNumber: -1  groupName:@"lanthanides"  period: 6 name:@"samarium"      roundedMass: 150.4  mass: 150.36     meltingPoint: 1074 boilingPoint: 	1794 density: 	7.52 electroNegativity: 		 1.2 firstIonisation: 545 electronAffinity:  0    commonOxidation:@"3,2" 	      predictedConfiguration:@"[Xe] 6s2 4f6" 		       observedConfiguration:@"[Xe] 6s2 4f6"          ], 		    	       				  		    
            [PElement elementWithNumber: 63  abbreviation:@"Eu"  groupNumber: -1  groupName:@"lanthanides"  period: 6 name:@"europium"      roundedMass: 152    mass: 151.964    meltingPoint: 822 boilingPoint: 		1529 density: 	5.24 electroNegativity: 		 0 firstIonisation: 	547 electronAffinity:  0    commonOxidation:@"3,2" 	      predictedConfiguration:@"[Xe] 6s2 4f7" 		       observedConfiguration:@"[Xe] 6s2 4f7"          ], 		             	  	 	  		    
            [PElement elementWithNumber: 64  abbreviation:@"Gd"  groupNumber: -1  groupName:@"lanthanides"  period: 6 name:@"gadolinium"    roundedMass: 157.3  mass: 157.25     meltingPoint: 1313 boilingPoint: 	3273 density: 	7.9 electroNegativity: 		   1.2 firstIonisation: 593 electronAffinity:  0    commonOxidation:@"3" 		      predictedConfiguration:@"[Xe] 6s2 4f8" 		       observedConfiguration:@"[Xe] 6s2 4f8"          ], 		    	     				  		  
            [PElement elementWithNumber: 65  abbreviation:@"Tb"  groupNumber: -1  groupName:@"lanthanides"  period: 6 name:@"terbium"       roundedMass: 158.9  mass: 158.92534  meltingPoint: 1365 boilingPoint: 	3230 density: 	8.23 electroNegativity: 		 0 firstIonisation: 	566 electronAffinity:  0    commonOxidation:@"3,4" 	      predictedConfiguration:@"[Xe] 6s2 4f9" 		       observedConfiguration:@"[Xe] 6s2 4f9"          ], 		    	       		  		      
            [PElement elementWithNumber: 66  abbreviation:@"Dy"  groupNumber: -1  groupName:@"lanthanides"  period: 6 name:@"dysprosium"    roundedMass: 162.5  mass: 162.5      meltingPoint: 1412 boilingPoint: 	2567 density: 	8.55 electroNegativity: 		 1.2 firstIonisation: 573 electronAffinity:  0    commonOxidation:@"3" 		      predictedConfiguration:@"[Xe] 6s2 4f10" 		     observedConfiguration:@"[Xe] 6s2 4f10"         ],   		    	       				  		  
            [PElement elementWithNumber: 67  abbreviation:@"Ho"  groupNumber: -1  groupName:@"lanthanides"  period: 6 name:@"holmium"       roundedMass: 164.9  mass: 164.93032  meltingPoint: 1474 boilingPoint: 	2700 density: 	8.8 electroNegativity: 		   1.2 firstIonisation: 581 electronAffinity:  0    commonOxidation:@"3" 		      predictedConfiguration:@"[Xe] 6s2 4f11" 		     observedConfiguration:@"[Xe] 6s2 4f11"         ],   		    	     		  		      
            [PElement elementWithNumber: 68  abbreviation:@"Er"  groupNumber: -1  groupName:@"lanthanides"  period: 6 name:@"erbium"        roundedMass: 167.3  mass: 167.259    meltingPoint: 1529 boilingPoint: 	2868 density: 	9.07 electroNegativity: 		 1.2 firstIonisation: 589 electronAffinity:  0    commonOxidation:@"3" 		      predictedConfiguration:@"[Xe] 6s2 4f12" 		     observedConfiguration:@"[Xe] 6s2 4f12"         ],   		    	       			  		      
            [PElement elementWithNumber: 69  abbreviation:@"Tm"  groupNumber: -1  groupName:@"lanthanides"  period: 6 name:@"thulium"       roundedMass: 168.9  mass: 168.93421  meltingPoint: 1545 boilingPoint: 	1950 density: 	9.32 electroNegativity: 		 1.3 firstIonisation: 597 electronAffinity:  0    commonOxidation:@"3,2" 	      predictedConfiguration:@"[Xe] 6s2 4f13" 		     observedConfiguration:@"[Xe] 6s2 4f13"         ],   		    	       		  		      
            [PElement elementWithNumber: 70  abbreviation:@"Yb"  groupNumber: -1  groupName:@"lanthanides"  period: 6 name:@"ytterbium"     roundedMass: 173    mass: 173.04     meltingPoint: 819 boilingPoint: 		1196 density: 	6.97 electroNegativity: 		 0 firstIonisation: 	603 electronAffinity:  0    commonOxidation:@"3,2" 	      predictedConfiguration:@"[Xe] 6s2 4f14" 		     observedConfiguration:@"[Xe] 6s2 4f14"         ],   		    	       	  		 	  		    
            [PElement elementWithNumber: 71  abbreviation:@"Lu"  groupNumber: 3   groupName:@"lanthanides"  period: 6 name:@"lutetium"      roundedMass: 175    mass: 174.967    meltingPoint: 1663 boilingPoint: 	3402 density: 	9.84 electroNegativity: 		 1.3 firstIonisation: 524 electronAffinity:  0    commonOxidation:@"3" 		      predictedConfiguration:@"[Xe] 6s2 4f14 5d1" 		 observedConfiguration:@"[Xe] 6s2 4f14 5d1"     ],   		    	       			 	  		   	 
            [PElement elementWithNumber: 72  abbreviation:@"Hf"  groupNumber: 4   groupName:@"IV B"         period: 6 name:@"hafnium"       roundedMass: 178.5  mass: 178.49     meltingPoint: 2227 boilingPoint: 	4600 density: 	13.3 electroNegativity: 		 1.3 firstIonisation: 659 electronAffinity:  0    commonOxidation:@"4" 		      predictedConfiguration:@"[Xe] 6s2 4f14 5d2" 		 observedConfiguration:@"[Xe] 6s2 4f14 5d2"     ],   		    	       				  		    	       	 
            [PElement elementWithNumber: 73  abbreviation:@"Ta"  groupNumber: 5   groupName:@"V B"          period: 6 name:@"tantalum"      roundedMass: 181    mass: 180.9479   meltingPoint: 2996 boilingPoint: 	5425 density: 	16.6 electroNegativity: 		 1.5 firstIonisation: 761 electronAffinity:  -14  commonOxidation:@"5" 		      predictedConfiguration:@"[Xe] 6s2 4f14 5d3" 		 observedConfiguration:@"[Xe] 6s2 4f14 5d3"     ],   		  	       			 	  		  	       	 
            [PElement elementWithNumber: 74  abbreviation:@"W"   groupNumber: 6   groupName:@"VI B"         period: 6 name:@"tungsten"      roundedMass: 183.8  mass: 183.84     meltingPoint: 3410 boilingPoint: 	5660 density: 	19.3 electroNegativity: 		 2.4 firstIonisation: 770 electronAffinity:  -80  commonOxidation:@"6,4" 		    predictedConfiguration:@"[Xe] 6s2 4f14 5d4" 		 observedConfiguration:@"[Xe] 6s2 4f14 5d4"     ],   		  	       				  		  	       	 
            [PElement elementWithNumber: 75  abbreviation:@"Re"  groupNumber: 7   groupName:@"VII B"        period: 6 name:@"rhenium"       roundedMass: 186.2  mass: 186.207    meltingPoint: 3180 boilingPoint: 	5600 density: 	21 electroNegativity: 		   1.9 firstIonisation:760 electronAffinity:  -14  commonOxidation:@"+7,4,6" 	  predictedConfiguration:@"[Xe] 6s2 4f14 5d5" 		 observedConfiguration:@"[Xe] 6s2 4f14 5d5"     ],     		  	           	 
            [PElement elementWithNumber: 76  abbreviation:@"Os"  groupNumber: 8   groupName:@"VIII B"       period: 6 name:@"osmium"        roundedMass: 190.2  mass: 190.23     meltingPoint: 3045 boilingPoint: 	5030 density: 	22.6 electroNegativity: 		 2.2 firstIonisation: 840 electronAffinity:  -106 commonOxidation:@"+4,6,8" 	  predictedConfiguration:@"[Xe] 6s2 4f14 5d6" 		 observedConfiguration:@"[Xe] 6s2 4f14 5d6"     ],     			       				  	            	 
            [PElement elementWithNumber: 77  abbreviation:@"Ir"  groupNumber: 9   groupName:@"VIII B"       period: 6 name:@"iridium"       roundedMass: 192.2  mass: 192.217    meltingPoint: 2410 boilingPoint: 	4130 density: 	22.4 electroNegativity: 		 2.2 firstIonisation: 880 electronAffinity:  -30  commonOxidation:@"+4,3,6" 	  predictedConfiguration:@"[Xe] 6s2 4f14 5d7" 		 observedConfiguration:@"[Xe] 6s2 4f14 5d7"     ],     		  	       			  		          	 
            [PElement elementWithNumber: 78  abbreviation:@"Pt"  groupNumber: 10  groupName:@"VIII B"       period: 6 name:@"platinum"      roundedMass: 195.1  mass: 195.078    meltingPoint: 1772 boilingPoint: 	3827 density: 	21.4 electroNegativity: 		 2.3 firstIonisation: 870 electronAffinity:  -205 commonOxidation:@"4,2" 		    predictedConfiguration:@"[Xe] 6s2 4f14 5d8" 		 observedConfiguration:@"[Xe] 6s2 4f14 5d8"     ],   			       			  		       	 
            [PElement elementWithNumber: 79  abbreviation:@"Au"  groupNumber: 11  groupName:@"I B"          period: 6 name:@"gold"          roundedMass: 197    mass: 196.96655  meltingPoint: 1064 boilingPoint: 	3080 density: 	19.3 electroNegativity: 		 2.5 firstIonisation: 890 electronAffinity:  -223 commonOxidation:@"3,1" 		    predictedConfiguration:@"[Xe] 6s2 4f14 5d9" 		 observedConfiguration:@"[Xe] 6s2 4f14 5d9"     ],   			       		 	  		      	      	 
            [PElement elementWithNumber: 80  abbreviation:@"Hg"  groupNumber: 12  groupName:@"II B"         period: 6 name:@"mercury"       roundedMass: 200.6  mass: 200.59     meltingPoint: -38.9 boilingPoint: 	357 density: 		13.5 electroNegativity: 		 2 firstIonisation: 	1007 electronAffinity: -18  commonOxidation:@"2,1" 		    predictedConfiguration:@"[Xe] 6s2 4f14 5d10" 		 observedConfiguration:@"[Xe] 6s2 4f14 5d10"    ], 		  	         		  		    	      	 
            [PElement elementWithNumber: 81  abbreviation:@"Tl"  groupNumber: 13  groupName:@"III A"        period: 6 name:@"thallium"      roundedMass: 204.4  mass: 204.3833   meltingPoint: 303 boilingPoint: 		1457 density: 	11.9 electroNegativity: 		 1.6 firstIonisation: 589 electronAffinity:  -19  commonOxidation:@"1,3" 		    predictedConfiguration:@"[Xe] 6s2 4f14 5d10 6p1" observedConfiguration:@"[Xe] 6s2 4f14 5d10 6p1"],  		  	       	  	  		        	 
            [PElement elementWithNumber: 82  abbreviation:@"Pb"  groupNumber: 14  groupName:@"IV A"         period: 6 name:@"lead"          roundedMass: 207.2  mass: 207.2      meltingPoint: 327.5 boilingPoint: 	1740 density: 	11.4 electroNegativity: 		 2.3 firstIonisation: 723 electronAffinity:  -35  commonOxidation:@"2,4" 		    predictedConfiguration:@"[Xe] 6s2 4f14 5d10 6p2" observedConfiguration:@"[Xe] 6s2 4f14 5d10 6p2"],  		  	       	  		  		      	      	 
            [PElement elementWithNumber: 83  abbreviation:@"Bi"  groupNumber: 15  groupName:@"V A"          period: 6 name:@"bismuth"       roundedMass: 209    mass: 208.98038  meltingPoint: 271 boilingPoint: 		1560 density: 	9.75 electroNegativity: 		 2 firstIonisation: 	711 electronAffinity:  -92  commonOxidation:@"3,5" 		    predictedConfiguration:@"[Xe] 6s2 4f14 5d10 6p3" observedConfiguration:@"[Xe] 6s2 4f14 5d10 6p3"],  		  	       	   	  		    	      	 
            [PElement elementWithNumber: 84  abbreviation:@"Po"  groupNumber: 16  groupName:@"VI A"         period: 6 name:@"polonium"      roundedMass: 209    mass: 209        meltingPoint: 254 boilingPoint: 		962 density: 		9.32 electroNegativity: 		 2 firstIonisation: 	821 electronAffinity:  -183 commonOxidation:@"4,2" 		    predictedConfiguration:@"[Xe] 6s2 4f14 5d10 6p4" observedConfiguration:@"[Xe] 6s2 4f14 5d10 6p4"],  			         		   	  		  	      	 
            [PElement elementWithNumber: 85  abbreviation:@"At"  groupNumber: 17  groupName:@"VII A"        period: 6 name:@"astatine"      roundedMass: 210    mass: 210        meltingPoint: 302 boilingPoint: 		337 density: 		0 electroNegativity: 		     2.2 firstIonisation: 920 electronAffinity:  -270 commonOxidation:@"" 		      predictedConfiguration:@"[Xe] 6s2 4f14 5d10 6p5" observedConfiguration:@"[Xe] 6s2 4f14 5d10 6p5"],    			         		   	  		        	 
            [PElement elementWithNumber: 86  abbreviation:@"Rn"  groupNumber: 18  groupName:@"VIII A"       period: 6 name:@"radon"         roundedMass: 222    mass: 222        meltingPoint: -71 boilingPoint: 		-61.8 density: 	0.00973 electroNegativity: 	 0 firstIonisation: 	1042 electronAffinity: 0    commonOxidation:@"0" 	        predictedConfiguration:@"[Xe] 6s2 4f14 5d10 6p6" observedConfiguration:@"[Xe] 6s2 4f14 5d10 6p6"],  		    	   	  		   	  		           	 
            [PElement elementWithNumber: 87  abbreviation:@"Fr"  groupNumber: 1   groupName:@"I A"          period: 7 name:@"francium"      roundedMass: 223    mass: 223        meltingPoint: 27 boilingPoint: 	  677 density: 		0 electroNegativity: 		     0.7 firstIonisation: 380 electronAffinity:  -44  commonOxidation:@"1" 	        predictedConfiguration:@"[Rn] 7s1" 		           observedConfiguration:@"[Rn] 7s1"              ], 		  	         	     	  		  	       	 
            [PElement elementWithNumber: 88  abbreviation:@"Ra"  groupNumber: 2   groupName:@"II A"         period: 7 name:@"radium"        roundedMass: 226    mass: 226        meltingPoint: 700 boilingPoint: 		1140 density: 	5 electroNegativity: 		     0.9 firstIonisation: 509 electronAffinity:  0    commonOxidation:@"2" 	        predictedConfiguration:@"[Rn] 7s2" 		           observedConfiguration:@"[Rn] 7s2"              ], 		    	     	  		   	  		    	       	 
            [PElement elementWithNumber: 89  abbreviation:@"Ac"  groupNumber: -2  groupName:@"III B"        period: 7 name:@"actinium"      roundedMass: 227    mass: 227        meltingPoint: 1050 boilingPoint: 	3200 density: 	10.1 electroNegativity: 		 1.1 firstIonisation: 499 electronAffinity:  0    commonOxidation:@"3" 	        predictedConfiguration:@"[Rn] 7s2 5f1" 		       observedConfiguration:@"[Rn] 7s2 5f1"          ], 		    	       			     	  		          
            [PElement elementWithNumber: 90  abbreviation:@"Th"  groupNumber: -2  groupName:@"actinides"    period: 7 name:@"thorium"       roundedMass: 232.04 mass: 232.0381   meltingPoint: 1750 boilingPoint: 	4790 density: 	11.7 electroNegativity: 		 1.3 firstIonisation: 587 electronAffinity:  0    commonOxidation:@"4" 	        predictedConfiguration:@"[Rn] 7s2 5f2" 		       observedConfiguration:@"[Rn] 7s2 5f2"          ], 		    	       			  		    	  
            [PElement elementWithNumber: 91  abbreviation:@"Pa"  groupNumber: -2  groupName:@"actinides"    period: 7 name:@"protactinium"  roundedMass: 231.04 mass: 231.03588  meltingPoint: 1570 boilingPoint: 	4000 density: 	15.4 electroNegativity: 		 1.5 firstIonisation: 568 electronAffinity:  0    commonOxidation:@"5,4"        predictedConfiguration:@"[Rn] 7s2 5f3" 		       observedConfiguration:@"[Rn] 7s2 5f3"          ],  		    	       		  		  
            [PElement elementWithNumber: 92  abbreviation:@"U"   groupNumber: -2  groupName:@"actinides"    period: 7 name:@"uranium"       roundedMass: 238.03 mass: 238.02891  meltingPoint: 1132 boilingPoint: 	3818 density: 	19 electroNegativity: 		   1.4 firstIonisation: 598 electronAffinity:  0    commonOxidation:@"+6,3,4,5"   predictedConfiguration:@"[Rn] 7s2 5f4" 		       observedConfiguration:@"[Rn] 7s2 5f4"          ], 			    	       		  		    	  
            [PElement elementWithNumber: 93  abbreviation:@"Np"  groupNumber: -2  groupName:@"actinides"    period: 7 name:@"neptunium"     roundedMass: 237    mass: 237        meltingPoint: 640 boilingPoint: 		3900 density: 	20.2 electroNegativity: 		 1.4 firstIonisation: 605 electronAffinity:  0    commonOxidation:@"+5,3,4,6"   predictedConfiguration:@"[Rn] 7s2 5f5" 		       observedConfiguration:@"[Rn] 7s2 5f5"          ], 			    	       	  		   	  		  	  
            [PElement elementWithNumber: 94  abbreviation:@"Pu"  groupNumber: -2  groupName:@"actinides"    period: 7 name:@"plutonium"     roundedMass: 239    mass: 239        meltingPoint: 641 boilingPoint: 		3232 density: 	19.8 electroNegativity: 		 1.3 firstIonisation: 585 electronAffinity:  0    commonOxidation:@"+4,3,5,6"   predictedConfiguration:@"[Rn] 7s2 5f6" 		       observedConfiguration:@"[Rn] 7s2 5f6"          ], 			    	       	  		   	  		  	  
            [PElement elementWithNumber: 95  abbreviation:@"Am"  groupNumber: -2  groupName:@"actinides"    period: 7 name:@"americium"     roundedMass: 243    mass: 243        meltingPoint: 994 boilingPoint: 		2607 density: 	13.7 electroNegativity: 		 1.3 firstIonisation: 578 electronAffinity:  0    commonOxidation:@"+3,4,5,6"   predictedConfiguration:@"[Rn] 7s2 5f7" 		       observedConfiguration:@"[Rn] 7s2 5f7"          ], 			    	       	  		   	  		  	  
            [PElement elementWithNumber: 96  abbreviation:@"Cm"  groupNumber: -2  groupName:@"actinides"    period: 7 name:@"curium"        roundedMass: 247    mass: 247        meltingPoint: 1340 boilingPoint: 	0 density: 		  13.5 electroNegativity: 		 1.3 firstIonisation: 581 electronAffinity:  0    commonOxidation:@"3" 		      predictedConfiguration:@"[Rn] 7s2 5f8" 		       observedConfiguration:@"[Rn] 7s2 5f8"          ], 		    	         			   	  		    	  
            [PElement elementWithNumber: 97  abbreviation:@"Bk"  groupNumber: -2  groupName:@"actinides"    period: 7 name:@"berkelium"     roundedMass: 247    mass: 247        meltingPoint: 986 boilingPoint: 		0 density: 		  14 electroNegativity: 		   1.3 firstIonisation: 601 electronAffinity:  0    commonOxidation:@"3,4" 		    predictedConfiguration:@"[Rn] 7s2 5f9" 		       observedConfiguration:@"[Rn] 7s2 5f9"          ], 		    	           		   	  		  	  
            [PElement elementWithNumber: 98  abbreviation:@"Cf"  groupNumber: -2  groupName:@"actinides"    period: 7 name:@"californium"   roundedMass: 251    mass: 251        meltingPoint: 0 boilingPoint: 		  0 density: 		  0 electroNegativity: 		     1.3 firstIonisation: 608 electronAffinity:  0    commonOxidation:@"3" 		      predictedConfiguration:@"[Rn] 7s2 5f10" 	       observedConfiguration:@"[Rn] 7s2 5f10"         ],   		    	           		   	  	  	  
            [PElement elementWithNumber: 99  abbreviation:@"Es"  groupNumber: -2  groupName:@"actinides"    period: 7 name:@"einsteinium"   roundedMass: 252    mass: 252        meltingPoint: 0 boilingPoint: 		  0 density: 		  0 electroNegativity: 		     1.3 firstIonisation: 619 electronAffinity:  0    commonOxidation:@"3" 		      predictedConfiguration:@"[Rn] 7s2 5f11" 	       observedConfiguration:@"[Rn] 7s2 5f11"         ],   		    	           		   	  	  	  
            [PElement elementWithNumber: 100 abbreviation:@"Fm"  groupNumber: -2  groupName:@"actinides"    period: 7 name:@"fermium"       roundedMass: 257    mass: 257        meltingPoint: 0 boilingPoint: 		  0 density: 		  0 electroNegativity: 		     1.3 firstIonisation: 627 electronAffinity:  0    commonOxidation:@"3" 		      predictedConfiguration:@"[Rn] 7s2 5f12" 	       observedConfiguration:@"[Rn] 7s2 5f12"         ],   		    	           		   	  		    	
            [PElement elementWithNumber: 101 abbreviation:@"Md"  groupNumber: -2  groupName:@"actinides"    period: 7 name:@"mendelevium"   roundedMass: 258    mass: 258        meltingPoint: 0 boilingPoint: 		  0 density: 		  0 electroNegativity: 		     1.3 firstIonisation: 635 electronAffinity:  0    commonOxidation:@"3,2" 		    predictedConfiguration:@"[Rn] 7s2 5f13" 	       observedConfiguration:@"[Rn] 7s2 5f13"         ],   		    	           		   	  	  	
            [PElement elementWithNumber: 102 abbreviation:@"No"  groupNumber: -2  groupName:@"actinides"    period: 7 name:@"nobelium"      roundedMass: 259    mass: 259        meltingPoint: 0 boilingPoint: 		  0 density: 		  0 electroNegativity: 		     1.3 firstIonisation: 642 electronAffinity:  0    commonOxidation:@"2,3" 		    predictedConfiguration:@"[Rn] 7s2 5f14" 	       observedConfiguration:@"[Rn] 7s2 5f14"         ],   		    	           		   	  		  	
            [PElement elementWithNumber: 103 abbreviation:@"Lr"  groupNumber: 3   groupName:@"actinides"    period: 7 name:@"lawrencium"    roundedMass: 262    mass: 262        meltingPoint: 0 boilingPoint: 		  0 density: 		  0 electroNegativity: 		     0 firstIonisation: 	0 electronAffinity: 	 0    commonOxidation:@"3" 		      predictedConfiguration:@"[Rn] 7s2 5f14 6d1" 		 observedConfiguration:@"[Rn] 7s2 5f14 6d1"     ],   		      	           		   	  			  
            [PElement elementWithNumber: 104 abbreviation:@"Rf"  groupNumber: 4   groupName:@"IV B"         period: 7 name:@"rutherfordium" roundedMass: 261    mass: 261        meltingPoint: 0 boilingPoint: 		  0 density: 		  0 electroNegativity: 		     0 firstIonisation: 	0 electronAffinity: 	 0    commonOxidation:@"" 		      predictedConfiguration:@"[Rn] 7s2 5f14 6d2" 		 observedConfiguration:@"[Rn] 7s2 5f14 6d2"     ],     		      	           		   	   		      
            [PElement elementWithNumber: 105 abbreviation:@"Db"  groupNumber: 5   groupName:@"V B"          period: 7 name:@"dubnium"       roundedMass: 262    mass: 262        meltingPoint: 0 boilingPoint: 		  0 density: 		  0 electroNegativity: 		     0 firstIonisation: 	0 electronAffinity: 	 0    commonOxidation:@"" 		      predictedConfiguration:@"[Rn] 7s2 5f14 6d3" 		 observedConfiguration:@"[Rn] 7s2 5f14 6d3"     ],     		      	           		   	  		    		      
            [PElement elementWithNumber: 106 abbreviation:@"Sg"  groupNumber: 6   groupName:@"VI B"         period: 7 name:@"seaborgium"    roundedMass: 266    mass: 266        meltingPoint: 0 boilingPoint: 		  0 density: 		  0 electroNegativity: 		     0 firstIonisation: 	0 electronAffinity: 	 0    commonOxidation:@"" 		      predictedConfiguration:@"[Rn] 7s2 5f14 6d4" 		 observedConfiguration:@"[Rn] 7s2 5f14 6d4"     ],     		      	           		   	  				      
            [PElement elementWithNumber: 107 abbreviation:@"Bh"  groupNumber: 7   groupName:@"VII B"        period: 7 name:@"bohrium"       roundedMass: 264    mass: 264        meltingPoint: 0 boilingPoint: 		  0 density: 		  0 electroNegativity: 		     0 firstIonisation: 	0 electronAffinity: 	 0    commonOxidation:@"" 		      predictedConfiguration:@"[Rn] 7s2 5f14 6d5" 		 observedConfiguration:@"[Rn] 7s2 5f14 6d5"     ],     		      	           		   	  		    	      
            [PElement elementWithNumber: 108 abbreviation:@"Hs"  groupNumber: 8   groupName:@"VIII B"       period: 7 name:@"hassium"       roundedMass: 277    mass: 277        meltingPoint: 0 boilingPoint: 		  0 density: 		  0 electroNegativity: 		     0 firstIonisation: 	0 electronAffinity: 	 0    commonOxidation:@"" 		      predictedConfiguration:@"[Rn] 7s2 5f14 6d6" 		 observedConfiguration:@"[Rn] 7s2 5f14 6d6"     ],     		      	           		   	  		    	      
            [PElement elementWithNumber: 109 abbreviation:@"Mt"  groupNumber: 9   groupName:@"VIII B"       period: 7 name:@"meitnerium"    roundedMass: 268    mass: 268        meltingPoint: 0 boilingPoint: 		  0 density: 		  0 electroNegativity: 		     0 firstIonisation: 	0 electronAffinity: 	 0    commonOxidation:@"" 		      predictedConfiguration:@"[Rn] 7s2 5f14 6d7" 		 observedConfiguration:@"[Rn] 7s2 5f14 6d7"     ],     		      	           		   	  			      
            [PElement elementWithNumber: 110 abbreviation:@"Ds"  groupNumber: 10  groupName:@"VIII B"       period: 7 name:@"darmstadtium"  roundedMass: 281    mass: 281        meltingPoint: 0 boilingPoint: 		  0 density: 		  0 electroNegativity: 		     0 firstIonisation: 	0 electronAffinity: 	 0    commonOxidation:@"" 		      predictedConfiguration:@"[Rn] 7s2 5f14 6d8" 		 observedConfiguration:@"[Rn] 7s2 5f14 6d8"     ],     		      	           		   	  		     
            [PElement elementWithNumber: 111 abbreviation:@"Rg"  groupNumber: 11  groupName:@"I B"          period: 7 name:@"roentgentium"  roundedMass: 272    mass: 272        meltingPoint: 0 boilingPoint: 		  0 density: 		  0 electroNegativity: 		     0 firstIonisation: 	0 electronAffinity: 	 0    commonOxidation:@"" 		      predictedConfiguration:@"[Rn] 7s2 5f14 6d9" 		 observedConfiguration:@"[Rn] 7s2 5f14 6d9"     ],     		      	           		   	  			     
            [PElement elementWithNumber: 112 abbreviation:@"Uub" groupNumber: 12  groupName:@"II B"         period: 7 name:@"ununbium"      roundedMass: 285    mass: 285        meltingPoint: 0 boilingPoint: 		  0 density: 		  0 electroNegativity: 		     0 firstIonisation: 	0 electronAffinity: 	 0    commonOxidation:@"" 		      predictedConfiguration:@"[Rn] 7s2 5f14 6d10" 		 observedConfiguration:@"[Rn] 7s2 5f14 6d10"    ],   		      	           		   	  		  		    
            [PElement elementWithNumber: 113 abbreviation:@"Uut" groupNumber: 13  groupName:@"III A"        period: 7 name:@"ununtrium"     roundedMass: 284    mass: 284        meltingPoint: 0 boilingPoint: 		  0 density: 		  0 electroNegativity: 		     0 firstIonisation: 	0 electronAffinity: 	 0    commonOxidation:@"" 		      predictedConfiguration:@"[Rn] 7s2 5f14 6d10 7p1" observedConfiguration:@"[Rn] 7s2 5f14 6d10 7p1"],    		      	           		   	  		  	    
            [PElement elementWithNumber: 114 abbreviation:@"Uuq" groupNumber: 14  groupName:@"IV A"         period: 7 name:@"ununquadium"   roundedMass: 289    mass: 289        meltingPoint: 0 boilingPoint: 		  0 density: 		  0 electroNegativity: 		     0 firstIonisation: 	0 electronAffinity: 	 0    commonOxidation:@"" 		      predictedConfiguration:@"[Rn] 7s2 5f14 6d10 7p2" observedConfiguration:@"[Rn] 7s2 5f14 6d10 7p2"],    		      	           		   	  	  		    
            [PElement elementWithNumber: 115 abbreviation:@"Uup" groupNumber: 15  groupName:@"V A"          period: 7 name:@"ununpentium"   roundedMass: 288    mass: 288        meltingPoint: 0 boilingPoint: 		  0 density: 		  0 electroNegativity: 		     0 firstIonisation: 	0 electronAffinity: 	 0    commonOxidation:@"" 		      predictedConfiguration:@"[Rn] 7s2 5f14 6d10 7p3" observedConfiguration:@"[Rn] 7s2 5f14 6d10 7p3"],    		      	           		   	  	  		    
            [PElement elementWithNumber: 116 abbreviation:@"Uuh" groupNumber: 16  groupName:@"VI A"         period: 7 name:@"ununhexium"    roundedMass: 292    mass: 292        meltingPoint: 0 boilingPoint: 		  0 density: 		  0 electroNegativity: 		     0 firstIonisation: 	0 electronAffinity: 	 0    commonOxidation:@"" 		      predictedConfiguration:@"[Rn] 7s2 5f14 6d10 7p4" observedConfiguration:@"[Rn] 7s2 5f14 6d10 7p4"],    		      	           		   	  				    
            [PElement elementWithNumber: 117 abbreviation:@"Uus" groupNumber: 17  groupName:@"VII A"        period: 7 name:@"ununseptium"   roundedMass: 0      mass: 0          meltingPoint: 0 boilingPoint: 		  0 density: 		  0 electroNegativity: 		     0 firstIonisation: 	0 electronAffinity: 	 0    commonOxidation:@"" 		      predictedConfiguration:@"[Rn] 7s2 5f14 6d10 7p5" observedConfiguration:@"[Rn] 7s2 5f14 6d10 7p5"],    		      	           		       	  	  	    
            [PElement elementWithNumber: 118 abbreviation:@"Uuo" groupNumber: 18  groupName:@"VIII A"       period: 7 name:@"ununoctium"    roundedMass: 294    mass: 294        meltingPoint: 0 boilingPoint: 		  0 density: 		  0 electroNegativity: 		     0 firstIonisation: 	0 electronAffinity: 	 0    commonOxidation:@"" 		      predictedConfiguration:@"[Rn] 7s2 5f14 6d10 7p6" observedConfiguration:@"[Rn] 7s2 5f14 6d10 7p6"],    		      							nil];
}
- (void) dealloc
{
	self.elements = nil;
	[super dealloc];
}

@end
